"""A file for cutting programs generated by a script

This module cuts a file made up of multiple programs into individual files.

Maintainer: agua@ciencias.unam.mx
"""

folder = "programs/"

"""'Cuts' a file of the form:
program0
=========
program1
=========
...
programn
=========
Into n different files named 
i.imp to i+n.imp

Parameters
----------
name : string
       Name of file.
i : int
    Starting number.
""" 
def cut(name, i):
    f = open(name, "r")
    current = i
    w = open(folder + str(i) + ".imp", "a")
    for line in f:
        if w.closed:
            w = open(folder + str(i) + ".imp", "a")
        # If at the end of the program.
        if line[0] == "=":
            w.close()
            i += 1
        else:
            w.write(line)

def write_numbers(i, j):
    f = open("programs.txt", "a")
    for n in range(i, j):
        f.write(str(n)+"\n");

write_numbers(0, 400000)            
#cut("programs500000-1000000.txt", 500000)
