name:                ResultChecker
version:             0.1.0.0
github:              "githubuser/ResultChecker"
license:             MIT
author:              "Victor Zamora"
maintainer:          "agua@ciencias.unam.mx"
copyright:           "2021 Victor Zamora"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ResultChecker#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- integer-logarithms
- parsec
- pureMD5
- random
- sort
- strict
- time

library:
  source-dirs: src

executables:
  ResultChecker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ResultChecker

tests:
  ResultChecker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ResultChecker
