name:                ArrayInterpreter
version:             0.1.0.0
github:              "victorz3/IMP-Language-Interpreter/ArrayInterpreter"
license:             GPL-3
author:              "Victor Zamora"
maintainer:          "agua@ciencias.unam.mx"
copyright:           "2021 Victor Zamora"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ArrayInterpreter#readme>

dependencies:
- base >= 4.7 && < 5
- integer-logarithms
- parsec
- vector

library:
  source-dirs: src

executables:
  ArrayInterpreter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ArrayInterpreter

tests:
  ArrayInterpreter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ArrayInterpreter
